package com.example.cattlelog.entities

import androidx.room.ColumnInfo
import androidx.room.Entity

@Entity (tableName = "cattle", primaryKeys = ["TagNumber", "BirthDate"])
data class Cattle(@ColumnInfo(name = "TagNumber") val TagNumber: Int,
                  @ColumnInfo(name = "BirthDate") val BirthDate: String,
                  @ColumnInfo(name = "DaysSinceBredHeat") val DaysSinceBredHeat: Int? = null,
                  @ColumnInfo(name = "DaysTilDue") val DaysTilDue: Int? = null,
                  @ColumnInfo(name = "GroupNumber") val GroupNumber: Int? = null,
                  @ColumnInfo(name = "TempGroupNumber") val TempGroupNumber: Int? = null,
                  @ColumnInfo(name = "ReproCode") val ReproCode: String? = null,
                  @ColumnInfo(name = "TimesBred") val TimesBred: Int? = null,
                  @ColumnInfo(name = "Breed") val Breed: String? = null,
                  @ColumnInfo(name = "UsrDef1") val UsrDef1: String? = null,
                  @ColumnInfo(name = "UsrDef2") val UsrDef2: String? = null,
                  @ColumnInfo(name = "UsrDef3") val UsrDef3: String? = null,
                  @ColumnInfo(name = "UsrDef4") val UsrDef4: String? = null,
                  @ColumnInfo(name = "UsrDef5") val UsrDef5: String? = null,
                  @ColumnInfo(name = "UsrDef6") val UsrDef6: String? = null,
                  @ColumnInfo(name = "UsrDef7") val UsrDef7: String? = null,
                  @ColumnInfo(name = "UsrDef8") val UsrDef8: String? = null,
                  @ColumnInfo(name = "UsrDef9") val UsrDef9: String? = null,
                  @ColumnInfo(name = "UsrDef10") val UsrDef10: String? = null,
                  @ColumnInfo(name = "DaysTilNextHeat") val DaysTilNextHeat: Int? = null,
                  @ColumnInfo(name = "BarnName") val BarnName: String? = null,
                  @ColumnInfo(name = "DHIID") val DHIID: String? = null,
                  @ColumnInfo(name = "DamIndex") val DamIndex: Int? = null,
                  @ColumnInfo(name = "DamName") val DamName: String? = null,
                  @ColumnInfo(name = "SireNameCode") val SireNameCode: String? = null,
                  @ColumnInfo(name = "TimesBredDate") val TimesBredDate: String? = null,
                  @ColumnInfo(name = "DateDue") val DateDue: String? = null,
                  @ColumnInfo(name = "ServiceSireNameCode") val ServiceSireNameCode: String? = null,
                  @ColumnInfo(name = "NextExpHeat") val NextExpHeat: String? = null,
                  @ColumnInfo(name = "AgeInMonthsAtCalving") val AgeInMonthsAtCalving: Int? = null,
                  @ColumnInfo(name = "DonorDamID") val DonorDamID: String? = null,
                  @ColumnInfo(name = "FarmID") val FarmID: String? = null,
                  @ColumnInfo(name = "DamDHI_ID") val DamDHI_ID: String? = null,
                  @ColumnInfo(name = "PrevBredHeat1") val PrevBredHeat1: String? = null,
                  @ColumnInfo(name = "PrevBredHeat2") val PrevBredHeat2: String? = null,
                  @ColumnInfo(name = "PrevBredHeat3") val PrevBredHeat3: String? = null,
                  @ColumnInfo(name = "WeightBirth") val WeightBirth: Int? = null,
                  @ColumnInfo(name = "WeightWean") val WeightWean: Int? = null,
                  @ColumnInfo(name = "WeightBred") val WeightBred: Int? = null,
                  @ColumnInfo(name = "WeightPuberty") val WeightPuberty: Int? = null,
                  @ColumnInfo(name = "WeightCalving") val WeightCalving: Int? = null,
                  @ColumnInfo(name = "DaysInCurGroup") val DaysInCurGroup: Int? = null,
                  @ColumnInfo(name = "DateLeft") val DateLeft: String? = null,
                  @ColumnInfo(name = "Reason") val Reason: String? = null
                  )